create table "public"."best_plays_test" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "old_best_plays" jsonb,
    "new_best_plays" jsonb,
    "stock_id" bigint
);


alter table "public"."best_plays_test" enable row level security;

CREATE UNIQUE INDEX best_plays_test_pkey ON public.best_plays_test USING btree (id);

alter table "public"."best_plays_test" add constraint "best_plays_test_pkey" PRIMARY KEY using index "best_plays_test_pkey";

grant delete on table "public"."best_plays_test" to "anon";

grant insert on table "public"."best_plays_test" to "anon";

grant references on table "public"."best_plays_test" to "anon";

grant select on table "public"."best_plays_test" to "anon";

grant trigger on table "public"."best_plays_test" to "anon";

grant truncate on table "public"."best_plays_test" to "anon";

grant update on table "public"."best_plays_test" to "anon";

grant delete on table "public"."best_plays_test" to "authenticated";

grant insert on table "public"."best_plays_test" to "authenticated";

grant references on table "public"."best_plays_test" to "authenticated";

grant select on table "public"."best_plays_test" to "authenticated";

grant trigger on table "public"."best_plays_test" to "authenticated";

grant truncate on table "public"."best_plays_test" to "authenticated";

grant update on table "public"."best_plays_test" to "authenticated";

grant delete on table "public"."best_plays_test" to "service_role";

grant insert on table "public"."best_plays_test" to "service_role";

grant references on table "public"."best_plays_test" to "service_role";

grant select on table "public"."best_plays_test" to "service_role";

grant trigger on table "public"."best_plays_test" to "service_role";

grant truncate on table "public"."best_plays_test" to "service_role";

grant update on table "public"."best_plays_test" to "service_role";


