alter table "public"."whitelist" drop constraint "whitelist_user_id_fkey";

alter table "public"."whitelist" drop constraint "whitelist_pkey";

drop index if exists "public"."whitelist_pkey";

alter table "public"."whitelist" drop column "user_id";

alter table "public"."whitelist" add column "id" bigint generated by default as identity not null;

CREATE UNIQUE INDEX whitelist_pkey ON public.whitelist USING btree (id);

alter table "public"."whitelist" add constraint "whitelist_pkey" PRIMARY KEY using index "whitelist_pkey";


